CREATE TABLE EMPLOYEE(
EMPID INT,
ENAME VARCHAR(20),
DEPARTMENT VARCHAR(20),
MANAGERID INT
);

INSERT INTO EMPLOYEE
VALUES
(1, 'ALICE', 'HR', NULL),
(2, 'BOB', 'FINANCE', 1),
(3, 'CHARLIE', 'IT', 1),
(4, 'D', 'FINANCE', 2),
(5, 'E', 'IT', 3),
(6, 'F', 'HR', 1);

SELECT E1.ENAME AS [EMPLOYEE NAME], E2.ENAME AS [MANAGER NAME],
	   E1.DEPARTMENT AS [EMPLOYEE_DEPT], E2.DEPARTMENT AS [MANAGER_DEPT] 
FROM EMPLOYEE AS E1
LEFT OUTER JOIN 
EMPLOYEE AS E2
ON E1.MANAGERID = E2.EMPID;
