CREATE TABLE AUTHOR(
AUTHOR_ID INT PRIMARY KEY,
AUTHOR_NAME VARCHAR(20),
COUNTRY VARCHAR(20)
)
CREATE TABLE BOOK (
BOOK_ID INT PRIMARY KEY,
BOOK_TITLE VARCHAR(20),
AUTHOR_ID INT  
FOREIGN KEY (AUTHOR_ID) 
REFERENCES AUTHOR(AUTHOR_ID)
)
INSERT INTO AUTHOR
VALUES
(1,'ANDREZ', 'POLAND’'),
(2,'MARTIN', 'USA'),
(3,'AMAN', 'INDIA'),
(4,'CARL', 'AUSTRALIA');

INSERT INTO BOOK
VALUES
(101,'SONG OF ICE AND FIRE', 2),
(102,'THE WITCHER', 1),
(103,'MONEY', 3),
(104,'SWORD', 4);

SELECT A.AUTHOR_NAME, A.COUNTRY , B.BOOK_TITLE
FROM AUTHOR  AS A
INNER JOIN
BOOK  AS B
ON 
A.AUTHOR_ID = B.AUTHOR_ID